<?php

namespace EmploiBundle\Repository;

/**
 * shs_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shs_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
