<?php

namespace EmploiBundle\Repository;

/**
 * shs_emploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shs_emploiRepository extends \Doctrine\ORM\EntityRepository
{
}
