<?php

namespace EmploiBundle\Repository;

/**
 * shs_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shs_userRepository extends \Doctrine\ORM\EntityRepository
{
}
