<?php

namespace EmploiBundle\Repository;

/**
 * shs_contactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shs_contactRepository extends \Doctrine\ORM\EntityRepository
{
}
